# Generated by Django 4.2.4 on 2023-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list_contratos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="cliente_contrato",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="codigo",
            field=models.IntegerField(),
        ),
    ]
