# Generated by Django 4.2.4 on 2023-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list_contratos", "0003_contrato_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="observacoes",
            field=models.TextField(null=True),
        ),
    ]
