# Generated by Django 4.2.4 on 2023-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list_contratos", "0004_alter_contrato_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="ano",
            field=models.IntegerField(null=True),
        ),
    ]
