# Generated by Django 4.2.4 on 2023-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list_contratos", "0005_contrato_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
