# Generated by Django 4.2.4 on 2023-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("birthdate", models.DateField(null=True)),
                ("married", models.BooleanField(default=False)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
    ]
