# Generated by Django 4.2.4 on 2023-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="age",
        ),
        migrations.RemoveField(
            model_name="person",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="person",
            name="married",
        ),
    ]
